-- AlterTable
ALTER TABLE "job"
ADD COLUMN "Benefits" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "CompanyName" VARCHAR(128),
ADD COLUMN "Deadline" TIMESTAMP(3),
ADD COLUMN "EmploymentType" VARCHAR(32),
ADD COLUMN "Location" VARCHAR(128),
ADD COLUMN "Requirements" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "SalaryMax" INTEGER,
ADD COLUMN "SalaryMin" INTEGER,
ADD COLUMN "WorkMode" VARCHAR(32);
